### ISSUE TITLE
Random Error by total time measurement in the Bsptime function in foreach loop

### ISSUE THREAD

**Issue by Hallo951** [sujit-sahu/bmstdr#4]
I have discovered an error that random occurs in a non-parallelized foreach loop. I am using a foreach loop for the calculation of the cross-validation. The error is 

**"Error in { : task 1 failed - "argument is of length zero""** 

and refers to the total time measurement in the function Bsptime that you have built in. I haven't found out the exact line yet.

After various test runs, the error always occurs when it cannot calculate the "Total time taken" for whatever reason. The actual model (spTimer), is calculated correctly before and their output is also displayed correctly by spTimer. 

For the elimination of the error it would be the simplest to remove the total time measurement or to check this on ZERO. Possibly also another kind of the time measurement would be a solution.

Because of this sporadic error a current use of the function "Bsptime" within a foreach loop is unfortunately not possible.

My system:
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 17763)

Version bmstdr: 0.2.2

**Comment by Hallo951** [comment]
This issue can be closed, because it turned out that it is not caused by the total time measurement.

**Comment by sujit-sahu** [comment]
Thank you for double checking this.
