### ISSUE TITLE
No function for the "plotit" option

### ISSUE THREAD

**Issue by Hallo951** [sujit-sahu/bmstdr#5]
Since the new version, the plot can no longer be deactivated via the "plotit" option. No matter if you set the option TRUE or FALSE, the plot always appears.

My system:
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 17763)

Version bmstdr: 0.2.2

**Comment by sujit-sahu** [comment]
Please can you tell me which plot cannot be deactivated by sharing your model fitting code. I will fix the issue then. 

I will watch out for this globally in the next version.

**Comment by Hallo951** [comment]
I can no longer deactivate the plots that appear after modeling. In the previous version it was still possible.

I have written you something about the error in the prediction. Please test if the code line I wrote works for you. With me it does not work...

**Comment by sujit-sahu** [comment]
This will be acted upon in the next release version.
