### ISSUE TITLE
truncated distribution with two border???

### ISSUE THREAD

**Issue by Hallo951** [sujit-sahu/bmstdr#9]
Hi 

it is possible you can make a truncated distribution with two border (currently truncated distribution has one (bottom) border. The goal is to predict only in a defined range of values (in this case in the range 0 <= y <= 1 or also 0 <= y <= 100). My input data have a same range! 

If I create a GPP model (spTimer) without a truncated distribution, the prediction contains a lot of values < 0. This is not good for my case. If I use the truncated distribution with the lower limit = 0 instead, then my prediction does not contain any values < 0. That is already very good. 

Two questions: 
Does a limit of 0 mean that 0 is modeled in the distribution or only values > 0? 
How do I determine the correct/optimal lambda value for the option 'truncation.para'? Currently I use the default setting.

I would need the same however also for the upper limit. As far as I know, there are truncated distributions with 2 (upper and lower) limit (example [here](https://search.r-project.org/CRAN/refmans/Ecfun/html/truncdist.html), [here](https://search.r-project.org/CRAN/refmans/mnormt/html/mtruncnorm.html) and [here](https://search.r-project.org/CRAN/refmans/truncnorm/html/dtruncnorm.html)). 

For non-Bayesian regression, I always used the inflated beta distribution (value range: 0 <= x <= 1), which gave me predictions only within the defined range.

Is this possible?

**Comment by sujit-sahu** [comment]
Thanks for the suggestions.  Here are my answers: 
> Does a limit of 0 mean that 0 is modeled in the distribution or only values > 0?
0 is modelled in the sense that P(Y=0) is allowed to have a positive value depending on the fitting data. Obviously, P(Y>0) = 1-P(Y=0) will be set according to the model. 

>  How do I determine the correct/optimal lambda value for the option 'truncation.para'? Currently I use the default setting.

As far as I understand, lambda determines the power transformation. It will be safer to try a few values of lambda and then choose the optimal value according to some validation criteria. 

Setting an upper limit for the data, e.g. 0 <= y <= 100. 

That is a very interesting suggestion. But I do not think it has been implemented in the spTimer package. I do not see an easy way to implement that either.  One needs to write the whole model fitting code from scratch for this. 

But I think there can be a way out to model your data still with the existing code. Say you have 0<y<1. Then just apply either the inverse-logit or inverse-probit transformation z=Phi^{-1}(y). Then you can model z which can take any value on the real line. 

Please let me know what you think.
